# Generated by Django 5.0.1 on 2024-01-10 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('degree', models.CharField(blank=True, max_length=10)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.speciality')),
            ],
            options={
                'verbose_name': 'o’qituvchi',
                'verbose_name_plural': 'o’qituvchilar',
            },
        ),
    ]
